server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.233:3306/quartz?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 15
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #使用数据库存储定时任务
    job-store-type: jdbc
  #redis连接配置
  redis:
    host: 192.168.0.219
    port: 6379
    password: jhsz0603
    database: 1

#mybatis-plus配置
mybatis-plus:
  # Mapper.xml 文件位置 Maven 多模块项目的扫描路径需以 classpath*: 开头
  mapper-locations: classpath:mapper/*.xml
  # 全局策略配置
  global-config:
    db-config:
      # id类型
      id-type: auto
      #现场策略
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  #指定实体所在的位置
  type-aliases-package: com.joe.transactional.pojo
  configuration:
    # 驼峰命名法
    map-underscore-to-camel-case: true
    #空值上的调用设置器
    call-setters-on-nulls: true
    #日志策略
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl