/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_NativeAdd */

#ifndef _Included_com_jni_NativeAdd
#define _Included_com_jni_NativeAdd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_NativeAdd
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_NativeAdd_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
